### ISSUE TITLE
Community Onboarding Presentation

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#101]

**Comment by liberty7369** [comment]
https://docs.google.com/presentation/d/12JuLCMNb6ZLnt5nTsF4UejA47brh4QO-3LdSs3T6DX4/edit#slide=id.g12ee055a3c6_2_75 @vincenzospaghetti  - please review

**Comment by vincenzospaghetti** [comment]
Looks great!

The only suggestion I would add is maybe more of a focus on these things:

- *Behaviors:* Do X, Y, Z at SCRF. Like, citizenship, collaboration,
coaching, curiosity, problem solving, respect, teamwork, leadership --
communicating often, asking questions, share knowledge, find places to
build, make connections, help others engage in dialogue and learn about
web3, propose research...Things that tell people how to act here and how to
engage.

- *Emphasize Forum Engagement: *spend time on the Forum. Read, write, and
gain cred with SourceCred (opt in on Discord). Want to actively move people
over to the forum.

Let me know what you think.

**Comment by liberty7369** [comment]
Strong feedback! I’ll implement the suggestions and let you know when it’s
ready for eyes again.

**Comment by liberty7369** [comment]
@vincenzospaghetti I changed slides 8 & 9 to contain actionable items. Let me know your thoughts. If approved, let's move it to Paul & Woodrow for their eyes. Also, who would host this event? Happy to do it too

**Comment by zubepaul** [comment]
@Wood-Jack Could you please take a look?

**Comment by Wood-Jack** [comment]
Yes I can @zubepaul

**Comment by Wood-Jack** [comment]
Hey I looked over the slides @liberty7369. It looks good its clean,concise , and describes SCRF in an easy way.

**Comment by zubepaul** [comment]
@liberty7369 I like the move to actionable throughout the presentation. I think there is still some more room to discuss culture and an arc of activity within SCRF that we could add. Let's make this a discussion point in our next meeting.

**Comment by vincenzospaghetti** [comment]
any further review of this needed?

https://docs.google.com/presentation/d/12JuLCMNb6ZLnt5nTsF4UejA47brh4QO-3LdSs3T6DX4/edit

**Comment by zubepaul** [comment]
Review completed.
