### ISSUE TITLE
Offboarding Guide (7/15)

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/engagement#115]

**Comment by ttaloute** [comment]
The purpose of the Offboarding Guide is to manage the transition of a part-time/full-time employee to a community member. This entails the transfer of knowledge and responsibilities, limiting access and privileges to a system, and obtaining feedback on their experience with the organization. 

I put together a draft of what a document guide can look like here. Please add comments, questions and suggestions. 

One question I have for you all is do we want to have a separate document for each section - IT, Hiring, Exit Interviews, etc and compile it into a folder or keep it one document for now? I've seen different models where they are separated and ones where it is put together. 

Link to Offboarding Guide: https://docs.google.com/document/d/1oWXDXM5FAu841MD-9h7El7tBbS71l69DNARy1p_N6tw/edit.

@zubepaul @eleventh19 @vincenzospaghetti  @ghettodev

**Comment by zubepaul** [comment]
Also create a survey with:
- Docs working and links
- Feedback to type
- Future intentions
- Identify permissions (emails)

**Comment by zubepaul** [comment]
Initial draft and process done.
