### ISSUE TITLE
🗪 [🚧] Change Request - Threads, Live, Ticket Tool

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#12]
### Launch Ready Task List
- [ ] Schedule a meet with @SirAh0 to implement the change on test server
- [ ] Pick a launch window for this change to go live 
- [ ] Ensure your change is launch ready before the launch window
- [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success
- [ ] Document pipeline approval, if applicable @marvino3

### Benefits

Threads on Discord allow us to have side conversations without taking up space in the chat, causing users to have to scroll through the conversation.

LIVE on Discord enables us to have open and group invitation meetings while staying within Discord. We hope for this feature to be used for our Onboarding Bootcamp and other meetings.

Changes to roles on Discord is an implementation of takeaways from the Terms and Titles document.

### Change Request

1. Change roles on Discord - this can only come after Spreadsheet Valerie emailed out on June 1st is complete
- https://docs.google.com/spreadsheets/d/1biVGofWdECcfVezXmGKk0mWIicotN6ztjyrwytLK3kg/edit
2. Enable "thread" capabilities for WELCOME, #Introductions and APPLY-HERE, #questions
3. Enable SCRF LIVE channel in LIVE
4. Ticket - can't remember this one but Valerie knows it. Her and/or I will elaborate on this request soon

### People

@SirAh0

**Comment by SirAh0** [comment]
>4. Ticket - can't remember this one but Valerie knows it. Her and/or I will elaborate on this request soon

The bot dashboard didn't save one of the steps. This should be fixed tomorrow, I'm going to make a ticket for the fix and I will link it back here when it's ready.

**Comment by SirAh0** [comment]
Here is the issue
#13

**Comment by brian-scrf** [comment]
> Enable SCRF LIVE channel in LIVE
[🗪 [🚧] Change Request - Enable LIVE](https://github.com/smartcontractresearchforum/engagement/issues/14)

**Comment by brian-scrf** [comment]
> Enable "thread" capabilities for WELCOME, #Introductions and APPLY-HERE, #questions

[🗪 [🚧] Change Request - Enable Threads](https://github.com/smartcontractresearchforum/engagement/issues/15)

**Comment by SirAh0** [comment]
>Enable SCRF LIVE channel in LIVE

https://github.com/smartcontractresearchforum/engagement/issues/14

**Comment by SirAh0** [comment]
> Enable "thread" capabilities for WELCOME, #Introductions and APPLY-HERE, #questions

[🗪 [🚧] Change Request - Enable Threads](https://github.com/smartcontractresearchforum/engagement/issues/15)

**Comment by SirAh0** [comment]
This issue has been closed and split into individual issues.
