### ISSUE TITLE
Project: This Week in SCRF

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#121]
### Description
A weekly chat announcement of cultivated happenings/wins/projects/and areas of interest for the SCRF community. 
### Project Plan
- [ ] Create light [project proposal](https://docs.google.com/document/d/1mWVdz53TK5bAGnyvk9xS7V0nkGP7eOxNLaL8e2GOplQ/edit#heading=h.9xvwuxmfaxqg)
- [ ] Create format/style
- [ ] Implementation
- [ ] Evaluate trial

**Comment by zubepaul** [comment]
@marvino3 Could you link to any issues that you have that might be associated with this idea?

**Comment by zubepaul** [comment]
Problems to solve:
- Where do we submit updates and ideas?
- Who is responsible for following up and enforcing?
- Are SCRF recognitions a separate project that gets tapped by this?

How do we source this?
-Verticals need to give updates that go into this in a regular cadence

Next Steps
- Project proposal
- Meeting with Discovery
- @vincenzospaghetti

**Comment by eleventh19** [comment]
here are some of the relevant cards in discovery: https://github.com/smartcontractresearchforum/discovery/issues?q=is%3Aissue+is%3Aopen+newsletter

**Comment by zubepaul** [comment]
Combining with issue that was duplicated. This will close and be tracked in #153
