### ISSUE TITLE
CRM/database research (7/26)

### ISSUE THREAD

**Issue by ttaloute** [smartcontractresearchforum/engagement#124]

**Comment by ttaloute** [comment]
Proposal/description: 


Research is captured here: https://docs.google.com/spreadsheets/d/1TTPFS1SNTDbjGK6XKK2F6afQm2dModKxUIYYGkTI8XY/edit#gid=505142905

**Comment by zubepaul** [comment]
This needs a budget. Need to connect with @eleventh19 @ghettodev if no announcement by end of the first week of August 2022
