### ISSUE TITLE
Engagement Grant

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#128]
### Description
This engagement grant is to advance the discussion on 4 of the following threads.
MatMat is the recipient of this grant
### To Complete
- Pick 4 of the following threads to comment on
- Provide meaningful discussion on that thread. This means providing some unique analysis of the issue/research, justifies and proposes next steps in the research or application, connects the research to current events and demonstrates how that research helps us better think about the current event, and/or connects and synthesizes information from other threads on the SCRF forum with the thread you are working on to help us better understand the problems/solutions proposed in the thread you are working on. 
- Please link to and cite sources if you are using any in your comments
- When you have completed 4 comments, please tag @zubepaul in a response to this GitHub issue. 
### Thread options
*Please check a thread off when you have completed your comment. Only 4 are required for this grant*
- [ ] [Discussion Post: Are Soulbound Tokens the best way to create a trusted layer on the blockchain?](https://www.smartcontractresearch.org/t/discussion-post-are-soulbound-tokens-the-best-way-to-create-a-trusted-layer-on-the-blockchain/1705)
- [ ] [Research Summary: Decentralized Governance of Stablecoins with Closed Form Valuation](https://www.smartcontractresearch.org/t/research-summary-decentralized-governance-of-stablecoins-with-closed-form-valuation/1789)
- [ ] [Research Summary: Studying Bitcoin privacy attacks and their Impact on Bitcoin-based Identity Methods](https://www.smartcontractresearch.org/t/research-summary-studying-bitcoin-privacy-attacks-and-their-impact-on-bitcoin-based-identity-methods/1790)
- [ ] [Research Summary: Privacy Preserving Decentralized Netting](https://www.smartcontractresearch.org/t/research-summary-privacy-preserving-decentralized-netting/1782)
- [ ] [Research Summary - Penny Wise and Pound Foolish: Quantifying the Risk of Unlimited Approval of ERC20 Tokens on Ethereum](https://www.smartcontractresearch.org/t/research-summary-penny-wise-and-pound-foolish-quantifying-the-risk-of-unlimited-approval-of-erc20-tokens-on-ethereum/1795)
- [ ] [Research Summary: SOK: Blockchain Governance](https://www.smartcontractresearch.org/t/research-summary-sok-blockchain-governance/1768)
- [ ] [Research Summary: DO NOT RUG ON ME: ZERO-DIMENSIONAL SCAM DETECTION](https://www.smartcontractresearch.org/t/research-summary-do-not-rug-on-me-zero-dimensional-scam-detection/1554)
- [ ] [Research Summary: Machine Learning Guided Cross-Contract Fuzzing](https://www.smartcontractresearch.org/t/research-summary-machine-learning-guided-cross-contract-fuzzing/1420)

**Comment by Ulyssesmathew** [comment]
I have picked four threads as requested: 

1. Research Summary: Decentralized Governance of Stablecoins with Closed Form Valuation[](https://www.smartcontractresearch.org/t/research-summary-decentralized-governance-of-stablecoins-with-closed-form-valuation/1789) 

2. Research Summary: Studying Bitcoin privacy attacks and their Impact on Bitcoin-based Identity Methods

3. Research Summary: Privacy Preserving Decentralized Netting

4. Research Summary - Penny Wise and Pound Foolish: Quantifying the Risk of Unlimited Approval of ERC20 Tokens on Ethereum

**Comment by Ulyssesmathew** [comment]
Link to the draft: https://docs.google.com/document/d/1baTJc5C92GpkNBQjO926CWRBpA5BwHFN3H8TNTV6v-k/edit?usp=drivesdk

**Comment by zubepaul** [comment]
@Ulyssesmathew Are you looking to collaborate/get feedback before posting, is that why the draft is linked here?

**Comment by Ulyssesmathew** [comment]
@zubepaul yes, I felt you might want to take a look before I send out. But if that's not necessary,  we can skip it.

**Comment by zubepaul** [comment]
@Ulyssesmathew I would be happy to take a look over things if you would like. It is not required, but I am happy to work with you on them.

**Comment by Ulyssesmathew** [comment]
@zubepaul noted. I will notify you once it's ready for you to have a look.

**Comment by Ulyssesmathew** [comment]
> ### Description
> This engagement grant is to advance the discussion on 4 of the following threads. MatMat is the recipient of this grant
> 
> ### To Complete
> * Pick 4 of the following threads to comment on
> * Provide meaningful discussion on that thread. This means providing some unique analysis of the issue/research, justifies and proposes next steps in the research or application, connects the research to current events and demonstrates how that research helps us better think about the current event, and/or connects and synthesizes information from other threads on the SCRF forum with the thread you are working on to help us better understand the problems/solutions proposed in the thread you are working on.
> * Please link to and cite sources if you are using any in your comments
> * When you have completed 4 comments, please tag @zubepaul in a response to this GitHub issue.
> 
> ### Thread options
> _Please check a thread off when you have completed your comment. Only 4 are required for this grant_
> 
> * [ ]  [Discussion Post: Are Soulbound Tokens the best way to create a trusted layer on the blockchain?](https://www.smartcontractresearch.org/t/discussion-post-are-soulbound-tokens-the-best-way-to-create-a-trusted-layer-on-the-blockchain/1705)
> * [ ]  [Research Summary: Decentralized Governance of Stablecoins with Closed Form Valuation](https://www.smartcontractresearch.org/t/research-summary-decentralized-governance-of-stablecoins-with-closed-form-valuation/1789)
> * [ ]  [Research Summary: Studying Bitcoin privacy attacks and their Impact on Bitcoin-based Identity Methods](https://www.smartcontractresearch.org/t/research-summary-studying-bitcoin-privacy-attacks-and-their-impact-on-bitcoin-based-identity-methods/1790)
> * [x]  [Research Summary: Privacy Preserving Decentralized Netting](https://www.smartcontractresearch.org/t/research-summary-privacy-preserving-decentralized-netting/1782)
> * [ ]  [Research Summary - Penny Wise and Pound Foolish: Quantifying the Risk of Unlimited Approval of ERC20 Tokens on Ethereum](https://www.smartcontractresearch.org/t/research-summary-penny-wise-and-pound-foolish-quantifying-the-risk-of-unlimited-approval-of-erc20-tokens-on-ethereum/1795)
> * [ ]  [Research Summary: SOK: Blockchain Governance](https://www.smartcontractresearch.org/t/research-summary-sok-blockchain-governance/1768)
> * [ ]  [Research Summary: DO NOT RUG ON ME: ZERO-DIMENSIONAL SCAM DETECTION](https://www.smartcontractresearch.org/t/research-summary-do-not-rug-on-me-zero-dimensional-scam-detection/1554)
> * [ ]  [Research Summary: Machine Learning Guided Cross-Contract Fuzzing](https://www.smartcontractresearch.org/t/research-summary-machine-learning-guided-cross-contract-fuzzing/1420)

**Comment by Ulyssesmathew** [comment]
Hi @zubepaul, this is to notify you that the work is ready for your consideration. 

Best regards,
Matthew

**Comment by zubepaul** [comment]
Looks great and I look forward to them being on the forum! 
When billing for this grant, you may link to this issue as evidence of completion once the comments are on the forum.

**Comment by Ulyssesmathew** [comment]
Alright, thank you!

**Comment by zubepaul** [comment]
Thank you for your work, grant reviewed and approved by Engagement team.
