### ISSUE TITLE
🗪 [🤖] Bad Bot - Ticket Tool Configuration

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#13]
### Bot Name

Ticket Tool

### Describe Problem

The Ticket Tool for the onboarding #apply-here channel is missing a few configurations.

@vincenzospaghetti
- [ ] Please list the changes needed as a comment to this issue.

**Comment by vincenzospaghetti** [comment]
https://docs.google.com/document/d/17emRq-FFycF2Y-9hvyJXn7OnG6zFFDOiTSQ9Pr4o4lo/edit?usp=sharing

Here is a doc outlining the changes! The changes needed are also on the Test Net. 

Here are some images from the Test Net.

![image](https://user-images.githubusercontent.com/93289575/171881645-df821aa7-aa15-4104-a878-5c1397bccaab.png)

![image](https://user-images.githubusercontent.com/93289575/171881706-5d26031a-5699-4c75-8909-1f804dbb553d.png)

![image](https://user-images.githubusercontent.com/93289575/171881741-1114a1d8-d084-4bcf-bc0f-b6125b4874b9.png)

**Comment by SirAh0** [comment]
Steps are also listed here
https://docs.google.com/document/d/17emRq-FFycF2Y-9hvyJXn7OnG6zFFDOiTSQ9Pr4o4lo/
