### ISSUE TITLE
🗪 [🚧] August Channel Audit

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#135]
### About
Evaluate the state of the Discord server to determine if each channel and category is serving a useful purpose. 

**Goal**
Reduce the number of channels and simplify the server.

**Criteria**
- empty channel
- low activity
- non-relevant information

**Actions**
- Merge channels
- move into the 🪓 Chopping Block
- refresh content

This list will be discussed in the upcoming Guild Meet.

**Comment by SirAh0** [comment]
#comment-of-the-month
https://discord.com/channels/784234332617048065/916428390750367754

@Wood-Jack  is heading up this effort. Lets figure out what to do with it.

**Comment by SirAh0** [comment]
📘directory last update 4/10/22

🏟scrf-events-chat feels redundant with new features that allow chat within Live channel. Reccomend archive.

📼recordings keep traffic pointing to YouTube - archive

🐦socials - chopping block - talk to discovery. Overly dividing traffic into too many places. Put socials into community channel. Social rollups speak with Outreach to extend their rollups. @ralphlombreglia @marvino3 @MichaelSCRF 

LIVE - Does SCRF need synchronous moments in Chat? Does SCRF need or even want un-recorded meets. Culturally aligned?  Wont replace Google Meets. 
Pro: lots of influx of members from other communities. Be used by cross pollination. 

💲bounties - 5/19 stale information, placeholder text. @vincenzospaghetti 
conflicting messaging

consolidate bounty, grant, open-positions into the APPLY HERE section as applications

💲sourcecred-opt-in remove it from OPPORTUNITES move to APPLY HERE

Shut down OPPORTUNIES category

Remove All vertical Categories - delete

📼-recordings team internal - delete

aiot - stale - no content since 12/10 - chopping block

**Comment by zubepaul** [comment]
- Comment of the month is hopefully migrating to the forum once the Community Category exists. Tracked in issue #86 
- There are several plans that would make use of Live that could potentially grow and strengthen community.

**Comment by SirAh0** [comment]
**Archive**
All current chopping block

**Comment by Wood-Jack** [comment]
Are we Chopping it today?

**Comment by SirAh0** [comment]
Today and through the weekend I will be making changes.

**Comment by SirAh0** [comment]
**Chopping Block**
- 🐦socials
- linkedin
- twitter
- 🏟scrf-events-chat

**Deleted**
Internal Vertical categories and their channels. Project specific channels will be added as needed within the SCRF Team category. 

**New Bots**
Craig for Live recording
StatBot for metrics

**Bot Changes**
Head role can now use the /GiveRole command to assign roles Lead and below roles.

**New Roles**
Recorder - Allows 

Announcer

**Comment by SirAh0** [comment]
**Moved Channels**
source-cred-opt-in moved to APPLY HERE
