### ISSUE TITLE
Community Category Creation and Launch

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#141]
### Description
This issue tracks the creation of the newly voted for Community Category on the forum, the documentation for new content types, and the announcement and rollout plan. 

### Steps
- [x] Write about section
- [x] SCRF recommends documentation
- [x] Community call documentation
- [x] Create Category
- [x] Launch day plan

**Comment by zubepaul** [comment]
Next step is to schedule a meeting to organize and get rolling on tasks.

**Comment by 0xAngle** [comment]
I replied in discord with meeting times, could you confirm those are fine
with you?

Thanks,
Angel

**Comment by zubepaul** [comment]
Use the link below to indicate availability so we can meet in the next 7 days
https://lettucemeet.com/l/J3WdA

**Comment by zubepaul** [comment]
@ufkhan97 Is going to create an initial document and link to this issue so we can start coordinating there as well.

**Comment by RuthTolulope** [comment]
Done

**Comment by ufkhan97** [comment]
> @ufkhan97 Is going to create an initial document and link to this issue so we can start coordinating there as well.

Doc started here: https://docs.google.com/document/d/1u1iMng_IcZqXAb1TRQVg1EoIg4XgYZHeIWFNpg20wvY/edit 

Please let me know if anyone needs edit permissions

**Comment by ufkhan97** [comment]
Paul, Angel and I met this morning and continued working on launching the community section of the forum. We decided to:

- Target: Friday, April 19th as a Launch Date
- Have some content ready to go on launch

To Do after this meeting:
- [ ] Update the About doc, flesh out post-type descriptions, and blurb about joining the chat. Add any links to documentation/further reading 
- [ ] Comb through the Meta section of the forum to identify what can go into the community section (and also look at SCRF Interview posts)

**Comment by RuthTolulope** [comment]
>  Start collating a list of best resources for onboarding to Web3, to be part of a SCRF Recommends post: https://docs.google.com/document/d/1xbEDvFBdWk22piaX67YKvTpU2mGihrIk9CCA9FaP3ps/edit?usp=sharing

I added more sections and some items to the SCRF recommends document.

**Comment by zubepaul** [comment]
Thank you @RuthTolulope for getting start on the SCRF recommends section. I am also thinking that the about section is pretty much done, but I do want to take at least one more read through it, but I hope all on this issue look and suggest as well. @0xAngle how is the taking a look at what should be in this new section going for you?

**Comment by 0xAngle** [comment]
Hi, yea I have a list

Based on "discussion about the SITE" description of META, these should be
moved since they are not related

All Reading Group Threads
Onboarding to SCRF ~maybe
SCRF Interviews
How can Discord benefit
Collaborative Research Proposal: A taxonomy and genealogy of
decentralization
SCRF Help Wanted
SCRF Weekly Community Calls
A collection of Blockchain Syllabi and Course Material
Research Pulse

**Comment by ufkhan97** [comment]
I made some slight tweaks to the "About" doc and added some links to it. Feeling good about this. 

Thank you @RuthTolulope for fleshing out the SCRF recommends document! I'll also add to this with some more examples as I dig around and hear from more folks

**Comment by zubepaul** [comment]
Proposed Launch Day Plan
- Create Category
- Migrate `meta` materials to `community`
- Create about pinned post
- Announce on Discord
- Have people here hype that up, especially @0xAngle and @ufkhan97 
- Help @MichaelSCRF promote via socials

**Comment by zubepaul** [comment]
For **Community Call** section, we will need to do some coordinated note taking to help socials as well. @0xAngle and @MichaelSCRF we should coordinate

**Comment by 0xAngle** [comment]
yes. I intend to start taking notes and making posts as soon as the
category is available.

**Comment by 0xAngle** [comment]
Do we have an idea of what the description / intention for types of posts
we want in this section?

**Comment by zubepaul** [comment]
Goals will be to provide a brief overview so that someone would know overall what happens, where subjects start end (with time indicators) and maybe some question primes for discussion. We can do some brainstorming together.

**Comment by 0xAngle** [comment]
Ok yea lets talk on that. Do we want to do this for Guild Meetings as well?

**Comment by zubepaul** [comment]
The Guilds should take care of their own notes, but we can discuss helping to model it. Category is now live.
- @ufkhan97 Could you please post the content about Notable Works and Key questions in a similar way to other categories? 
- @RuthTolulope Could you please start the  SCRF recommends post. 

Once those are done, please tag me as I will update the pinned post link to the director instead of the Gdocs.

**Comment by zubepaul** [comment]
@ufkhan97 @RuthTolulope 
Updates? I would like to be able to announce this via Discord and Socials this week

**Comment by ufkhan97** [comment]
@zubepaul Notable works thread up here: https://www.smartcontractresearch.org/t/notable-works-on-community/1942

I will try to research and seed the list with a couple pieces this week.

Definitely happy to help hype this up on discord when we're a go!

**Comment by zubepaul** [comment]
I agree with your instinct to differentiate it a little with the preface. Please edit to make that change @ufkhan97

**Comment by ufkhan97** [comment]
Updated!

**Comment by content-scrf** [comment]
Hi @zubepaul, I have updated the blurb on SCRF recommends here https://docs.google.com/document/d/1xbEDvFBdWk22piaX67YKvTpU2mGihrIk9CCA9FaP3ps/edit?usp=sharing
I am ready to post to the forum once approved.

**Comment by RuthTolulope** [comment]
Hi @zubepaul I have updated the blurb on the community section here https://docs.google.com/document/d/1xbEDvFBdWk22piaX67YKvTpU2mGihrIk9CCA9FaP3ps/edit?usp=sharing

I am ready to post to the forum once approved.

**Comment by zubepaul** [comment]
There are some tags to make as well, but then after that, we did the thing, team!

**Comment by MichaelSCRF** [comment]
Socials posts are now live! 

Twitter: https://twitter.com/SCRForum/status/1562872280283111431?s=20&t=9sdb1wD5fKu5Z1lQNjQRWA

LinkedIn: https://www.linkedin.com/posts/smart-contract-research-forum_community-activity-6968637963295485952-SDIi?utm_source=share&utm_medium=member_desktop
