### ISSUE TITLE
Valerie Offboarding Checklist

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#147]
The purpose of this ticket is to make sure to capture and continue the work Valerie was doing for onboarding and SCRF overall.

Linked here you'll find a checklist of things, new assignments of tasks, and important documents. All of these documents are now stored in the [Engagement Team Drive](https://drive.google.com/drive/u/1/folders/0AP0mjA_oIyg4Uk9PVA).

https://docs.google.com/document/d/1fWaLq9KRHQMoOkdQhbv0wZADfIAEDb7PppI4DTGRQgw/edit#

**Comment by vincenzospaghetti** [comment]
![Image](https://user-images.githubusercontent.com/93289575/184240370-797eb982-d72c-4359-9f75-75b8fd0e2b5d.JPG)

**Comment by vincenzospaghetti** [comment]
@ttaloute Just FYI - I have recommended you to PM/facilitate the Legal Working Group going forward. We are going to assess how much work is here and what the Working Group looks like for the next 30-60-90 (if at all).

@twan-dev

**Comment by zubepaul** [comment]
Most of these tasks are now assigned and in progress. Closing ticket and adding an additional thank you to @vincenzospaghetti
