### ISSUE TITLE
Engagement Grant

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#148]
### Description
This engagement grant is to advance the discussion on 4 of the following threads.
@mazewind is the recipient of this grant
### To Complete
- Pick 4 of the following threads to comment on
- Provide meaningful discussion on that thread. This means providing some unique analysis of the issue/research, justifies and proposes next steps in the research or application, connects the research to current events and demonstrates how that research helps us better think about the current event, and/or connects and synthesizes information from other threads on the SCRF forum with the thread you are working on to help us better understand the problems/solutions proposed in the thread you are working on. 
- Please link to and cite sources if you are using any in your comments
- When you have completed 4 comments, please tag @zubepaul in a response to this GitHub issue.

**Comment by mazewind** [comment]
@zubepaul I've completed the comments :)

**Comment by zubepaul** [comment]
Thank you for your great work. I would like to have a follow up with you (can be a meeting or through a chat) to talk about your experience with this grant.

You may also use this GH issue in your billing statement as evidence of completion if needed.

**Comment by mazewind** [comment]
Great, sounds good! I'd be up for either a chat or a call
