### ISSUE TITLE
🗪 [🚧] - Enable Threads

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#15]
### Launch Ready Task List
- [x] Schedule a meet with @SirAh0 to implement the change on test server
- [x] Pick a launch window for this change to go live 
- [x] Ensure your change is launch ready before the launch window
- [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success
- [ ] Document pipeline approval, if applicable @marvino3

### Benefits

>Threads on Discord allow us to have side conversations without taking up space in the chat, causing users to have to scroll through the conversation. 
- @liberty7369 

>need threads opened in the discord for organization of messaging. some chats are too messy to follow (introductions) - 
- @vincenzospaghetti 

>Using threads exclusively in #introductions channel is a good way to introduce a new feature to the community with minimum impact.
>It will solve a growing problem of conversations diluting the intention of the #introductions channel which is to give people an easy way to scroll up and read the introductions other people have left. Currently there is a lot of side chat occuring, information sharing, and other kinds of conversations that create a significant amount of separation between introductions. This makes the '#introductions` channel feel more like a chat room than a place to do a specific thing - introduce oneself.
>Enabling threads here will still allow for the side conversations to occur and in doing so preserve the intention of the channel.
>Only designated roles can create threads which will be Core or above - not the general community.
- @sirAh0

### Change Request

Enable Thread capabilities for 
- [>Welcome #introcductions](https://discord.com/channels/784234332617048065/962837657732407356)
- [> Apply Here #questions](https://discord.com/channels/784234332617048065/962837906001633361)

@ghettodev 

- [x] #17

@SirAh0 
- [ ] Enable threads for the  `>Welcome #introduction` channel once #17 is done.
- [ ] Enable threads for the `>Apply here #introduction` channel once #17 is done.

### People

@zubepaul @SirAh0 @vincenzospaghetti @ghettodev @liberty7369

**Comment by SirAh0** [comment]
- [ ] @ghettodev Update Discord Settings
In order to enable Threads, Discord Settings -> Roles -> Default Permissions

![image](https://user-images.githubusercontent.com/12703396/171788062-6a65db42-5ae9-41a6-a0c3-51221c2a5343.png)

Then enable **Create Public Threads** and **Manage Threads**

![image](https://user-images.githubusercontent.com/12703396/171788123-10769000-bb81-4866-97f6-f8cb7d6a2325.png)

- [ ] Enable threads only on the channels listed above in this ticket. @SirAh0

**Comment by Fizzymidas** [comment]
This is a cool one.

Will the threads have a fixed time in which they close when inactive?

**Comment by SirAh0** [comment]
> Will the threads have a fixed time in which they close when inactive?

I have worked with a bot before that can keep threads permanently open if we need to do that. From what I have gleaned on the channel, most side chats don't occur over a long period of time so I doubt it will be an issue.

**Comment by zubepaul** [comment]
I think there is a lot of utility being able to have these onboarding type conversations in the introduction channel. That said, I have two concerns:
1. Is there a plan for staffing/responsibility to connect with people?
2. Is there a plan to use these to get people out of the introduction channel and into the community chat in an engaged way?

**Comment by SirAh0** [comment]
Live

Public threads can be created by anyone with the `Core `role.

**Comment by vincenzospaghetti** [comment]
Brian - I want to make an announcement about this. What points do I need to
add?

**Comment by SirAh0** [comment]
Let's schedule a meeting for the onboarding folks that will be using this tool. I'm free anytime tomorrow.
