### ISSUE TITLE
🗪 [🚧] Change Request

### ISSUE THREAD

**Issue by jring-o** [smartcontractresearchforum/engagement#156]
### ⛽Fueled Task List

- [x] Schedule a meet with @SirAh0 to implement the change on test server
- [x] Pick a launch window for this change to go live 
- [x] Ensure your change is launch ready before the launch window
- [x] Schedule a follow up meeting with @SirAh0 to explain why this change was a success one month out
- [x] Document pipeline approval, if applicable @marvino3

### Benefits

Allow us to record voice on Discord.

### Change Request

Add the Craig recording bot to Discord. Lets us set people up to record voice sessions. 

https://craig.chat/

**Comment by SirAh0** [comment]
Craig has been added. Lets connect early next week and make sure its working as you need it to.
