### ISSUE TITLE
🗪 [📅] Calendar

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#174]
### Describe Problem

Need to change the Onboarding Bootcamp to the first Tuesday of every month instead of the first day of every month. This will take effect in October. @zubepaul will find a time that works

**Comment by SirAh0** [comment]
Let me know if the time changes.

I've updated the day to be the first Tuesday of each month.

https://github.com/smartcontractresearchforum/discovery/issues/110

https://discord.gg/BCUnKBvr?event=1015290198462050374

https://scrf.io/calendar
