### ISSUE TITLE
Engagement Grant: User Experience

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#188]
### Description
This grant is issued to Tomide to provide user experience improvements for 5 threads on the forum as described below. It is expected that this grant will take approximately 5-7 hours to complete
### Steps
- [x] Identify 5 [forum topics](https://www.smartcontractresearch.org/) with 10 or more responses. Link to those selected 5 comments below for review
- [x] Using this [grant document](https://docs.google.com/document/d/1UxckJYlwWbXg3Ypv7g0wlDf-yTMI9Lh17cMuforhxco/edit#heading=h.4v98jkc3utre) identify tags that would be helpful to add to each of the identified topics. Also use that document to propose additional topics that a person interested in each chosen thread would also want to read and engage with. 
- [x] For each proposed recommended to read, provide a short 1-2 sentence description why that would be good to read
- [ ] When completed, please tag @zubepaul in a comment below for review

**Comment by tomideadeoye** [comment]
Hi Paul, I don't have access to this [link](https://github.com/smartcontractresearchforum/engagement/issues/smartcontractresearch.org). 

I guess this was a mistake, and it should link to smartcontractresearch.org

**Comment by tomideadeoye** [comment]
Hi Paul, 
I am proposing:

1. Leveraging Blockchain for Greater Accessibility of Machine Learning Models https://www.smartcontractresearch.org/t/research-summary-leveraging-blockchain-for-greater-accessibility-of-machine-learning-models/808
2. SoK: Applying Blockchain Technology in Industrial Internet of Things https://www.smartcontractresearch.org/t/research-summary-sok-applying-blockchain-technology-in-industrial-internet-of-things/866
3. On the Economic Design of Stablecoins https://www.smartcontractresearch.org/t/research-summary-on-the-economic-design-of-stablecoins/817
4. Ethereum Name Service: the Good, the Bad, and the Ugly https://www.smartcontractresearch.org/t/research-summary-ethereum-name-service-the-good-the-bad-and-the-ugly/1587
5. What is in Your Wallet? Privacy and Security Issues in Web 3.0 https://www.smartcontractresearch.org/t/research-summary-what-is-in-your-wallet-privacy-and-security-issues-in-web-3-0/1225


They seem to have the shortest tags.

**Comment by zubepaul** [comment]
@tomideadeoye 
These are good selections. Please move on to the next step

**Comment by tomideadeoye** [comment]
Hi @zubepaul 

https://docs.google.com/document/d/1UxckJYlwWbXg3Ypv7g0wlDf-yTMI9Lh17cMuforhxco/edit?pli=1#heading=h.rr95njje5fad

**Comment by zubepaul** [comment]
@tomideadeoye 
Overall, these look good. I will update after a final review within 24 hours. In the meantime, several of these proposed tags are not currently on the forum. It would be good to recommend and advocate for them on the forum using the [SCRF Terms Glossary and Content Tags](https://www.smartcontractresearch.org/t/scrf-terms-glossary-and-content-tags/364)

**Comment by tomideadeoye** [comment]
Thanks, @zubepaul  I will collate those and add them to the thread.
