### ISSUE TITLE
🗪 [🔓] FORUM-NOTIFICATIONS - Make Private

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#22]
### Request

**User Role**
 @everyone
 @community

**Category Settings**
> FORUM-NOTIFICATIONS
 
**Set Private Category**
![image](https://user-images.githubusercontent.com/12703396/172236138-13ffd606-cf1d-4b0d-977e-4c57f4dd9e32.png)

**@everyone View Channels NO**
![image](https://user-images.githubusercontent.com/12703396/172236448-1157ccdf-3ab4-4a57-8eef-15182763c64d.png)

@community View Channels YES
![image](https://user-images.githubusercontent.com/12703396/172236486-956af13a-875a-481f-ae64-5c0a95863c76.png)

**Comment by ghettodev** [comment]
should be fixed now, pls confirm
