### ISSUE TITLE
🗪 [🔓] SCRF Discord User List

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/engagement#35]
### Reason for Issue
Currently we have a lot of people in Discord who are using the researcher role. The vertical roles as defined in [Terms and Titles ](https://docs.google.com/document/d/1_6v1vVUEV12UpSP8hN0Fq-TmvgHWEIejuiv6Cz1h23E/edit?usp=sharing) now need to be applied to the discord user list.

In order to launch the next round of changes to Discord Chat, a list needs to be created of all users in Discord and which vertical they are in and role. 

This will enable the sidebar list of users to be organized by role: Community, Contributor, Core, Head, Lead

**Tabbed Spreadsheet**
Please note that each vertical is listed in a separate tab at the bottom of the spreadsheet.

A [SCRF Discord User List](https://docs.google.com/spreadsheets/d/1EW2F5c34boav_MFJMJkpzOY-u3L0M1BDh10TaiZ1fvI/edit?usp=sharing) spreadsheet has been created. It will be used to roll out the new Chat Roles to the users of our community. 

### Request

Need a list of discord users per vertical for each tab in the spread sheet linked below.

- [x] Content @twan-dev 
- [x] Engagement @zubepaul 
- [x] Discovery @marvino3 
- [x] Outreach @eleventh19 
- [x] Operations @ghettodev @eleventh19 

**Spreadsheet**
➡️[SCRF Discord User List](https://docs.google.com/spreadsheets/d/1biVGofWdECcfVezXmGKk0mWIicotN6ztjyrwytLK3kg/edit#gid=0)

**Comment by twan-dev** [comment]
I think we need to come to terms with visibility and what info goes up before setting it up

**Comment by SirAh0** [comment]
This is a list of discord users and their role within the SCRF org which we are trying to make public through the Discord user list. 

This will enable, per the terms and title doc, the SCRF Discord server to sort the user list according to role. 

The purpose of the spreadsheet is to capture that list.

There is no information beyond the discord user name and the role in the org.

**Comment by SirAh0** [comment]
Feel free to just DM the list if you don't want to add it in the spreadsheet.
