### ISSUE TITLE
🗪 [🤖] Ticket Tool - Title, Colors

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#36]
### Bot Name

Ticket Tool for Onbaording

### Changes

https://tickettool.xyz/

![Image](https://user-images.githubusercontent.com/12703396/174329146-dabe7d72-eec8-430d-971f-9bb68fd4f626.png)

![image](https://user-images.githubusercontent.com/12703396/174330413-a895eb79-f70d-4af6-8639-126f5e8a9eb9.png)

Empty Message Text Field
![image](https://user-images.githubusercontent.com/12703396/174330978-e7e2f57c-4f98-48a5-8bd2-91622c59099d.png)

Empty Footer Fields
![image](https://user-images.githubusercontent.com/12703396/174331160-3fcb9916-1dcd-487c-b0a2-01ed6ee44210.png)

![image](https://user-images.githubusercontent.com/12703396/174331481-f6cf930c-0930-4c0f-b4c0-7c5362e98910.png)

Set Title to `Welcome to SCRF!`
![image](https://user-images.githubusercontent.com/12703396/174331745-64f29ffd-6ed2-42cd-b589-8b910e90b7dd.png)

Empty Field Message Text
![image](https://user-images.githubusercontent.com/12703396/174331815-d602ed77-023d-43b7-9b0a-a2990e88084d.png)

Color `#5865F2`

![image](https://user-images.githubusercontent.com/12703396/174331887-61c04a8e-257e-4a18-9ceb-4d2bb64ddf18.png)

**Comment by SirAh0** [comment]
Thank you, I'll expect to get this fixed on Monday 6/20

**Comment by SirAh0** [comment]
Duplicated sub-Issue, create DM

https://github.com/smartcontractresearchforum/engagement/issues/24

**Comment by ghettodev** [comment]
made the changes, let me know if there are any issues.

**Comment by SirAh0** [comment]
thank you
