### ISSUE TITLE
🗪 [🚧] Change Request

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#37]
### Launch Ready Task List

- [ ] Schedule a meet with @SirAh0 to implement the change on test server
- [ ] Pick a launch window for this change to go live 
- [ ] Ensure your change is launch ready before the launch window
- [ ] After a month, schedule a follow up meeting with @SirAh0 to explain why this change was a success
- [ ] Document pipeline approval, if applicable @marvino3

### Benefits

- need threads opened in the discord for organization of messaging. some chats are too messy to follow (introductions)

### Change Request

Open threads in the discord/chat

### People

- @sir

**Comment by SirAh0** [comment]
moved this issue to the main thread issue:
https://github.com/smartcontractresearchforum/engagement/issues/15
