### ISSUE TITLE
🗪 [🚧] Change Request

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#59]
### ⛽Fueled Task List

- [ ] Schedule a meet with @SirAh0 to implement the change on test server
- [ ] Pick a launch window for this change to go live 
- [ ] Ensure your change is launch ready before the launch window
- [ ] Schedule a follow up meeting with @SirAh0 to explain why this change was a success one month out
- [ ] Document pipeline approval, if applicable @marvino3

### Benefits

Tamar can see how many users enter the Discord

### Change Request

Please give #Liberty7369 permission to see the new users who enter Discord. I hear it can be found under the Apply Here section

**Comment by SirAh0** [comment]
You should have the required role to view the channel, here is the link and image let me know if you need more help!

https://discord.com/channels/784234332617048065/962843215931797584

![image](https://user-images.githubusercontent.com/12703396/175428612-f877daaa-d643-4afe-bcb5-a150c3057f9a.png)

**Comment by liberty7369** [comment]
<img width="234" alt="Screen Shot 2022-06-23 at 6 58 03 PM" src="https://user-images.githubusercontent.com/103522749/175434228-2e065314-a360-4bae-9734-b10832e150fa.png">

I don't see what you're seeing...

**Comment by SirAh0** [comment]
confirmed fixed.
