### ISSUE TITLE
Pre-onboarding checklist - message

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#61]

**Comment by liberty7369** [comment]
https://github.com/smartcontractresearchforum/research_team/issues/218

**Comment by liberty7369** [comment]
https://github.com/smartcontractresearchforum/research_team/issues/218

**Comment by liberty7369** [comment]
Document with message: https://docs.google.com/document/d/1pFCo_mlzC9-318DKCOk4IuLPzwetdeOevWRQBHqd0QQ/edit?usp=sharing

**Comment by liberty7369** [comment]
https://docs.google.com/document/d/18zsKOFF8b6RXnz6MYyUFW6rjkgbbx5IMsyJe5xuchsk/edit# @zubepaul

**Comment by vincenzospaghetti** [comment]
May or may not do this going forward. @0xAngle can decide. I would recommend just posting an announcement in #info on Discord. See my other posts as examples.

https://discord.com/channels/784234332617048065/968212233182134323
