### ISSUE TITLE
Form and/or tracking system for new hires: create and be assigned tickets - adding member to github, give member email address, share drive access, discord channel access, etc.

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#62]

**Comment by liberty7369** [comment]
https://github.com/smartcontractresearchforum/research_team/issues/218

**Comment by liberty7369** [comment]
This is part of a spreadsheet Valerie and I were working on last week. Need to link up with Lorretta and/or Tania so we can track the process and make sure tasks don't fall in between handoffs.

**Comment by SirAh0** [comment]
For reference, on the IT side here is where requests can be made. 

https://github.com/smartcontractresearchforum/IT/issues/new/choose

**Comment by SirAh0** [comment]
this one! 🚀

>issue is created for each individual (and it includes the list of items that individual needs access to)

**Comment by vincenzospaghetti** [comment]
we have made this: https://docs.google.com/spreadsheets/d/1GoLgXPF3SFpkUTUQDbkdcoGJ2rX13XNyGrsWVFrY4nY/edit#gid=0

If this looks good, we can mark as done. Please let me know if you have feedback:
@ghettodev @eleventh19 @zubepaul @SirAh0 @ttaloute @LorrettaGS @liberty7369

**Comment by vincenzospaghetti** [comment]
This ticket ties into another open ticket: https://github.com/smartcontractresearchforum/engagement/issues/63

This document has been created and I will close this ticket.

Going forward @0xAngle will manage this document alongside hiring.
