### ISSUE TITLE
Excel sheet for tracking legal names

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#63]

**Comment by ttaloute** [comment]
Will create and fill this out based on a list I compiled in early June of current contractors.

**Comment by zubepaul** [comment]
Any additional steps needed here?

**Comment by vincenzospaghetti** [comment]
Not sure if this ties into the onboarding and hiring tracker we created. This document is here: https://docs.google.com/spreadsheets/d/1GoLgXPF3SFpkUTUQDbkdcoGJ2rX13XNyGrsWVFrY4nY/edit

Going forward, @0xAngle will manage the Onboarding portion of this doc and make sure all new hires have what they need to be successful, using the doc as a checklist for him and hiring.
