### ISSUE TITLE
GitHub tutorial onboarding session

### ISSUE THREAD

**Issue by liberty7369** [smartcontractresearchforum/engagement#65]

**Comment by liberty7369** [comment]
https://github.com/smartcontractresearchforum/research_team/issues/218

**Comment by liberty7369** [comment]
This is to work with Brian and/or Woodrow to host a monthly GitHub tutorial session for those who are unfamiliar with the platform.

**Comment by SirAh0** [comment]
love it - lets have a meet and we can talk about some ideas.

Here is some related info:
https://github.com/smartcontractresearchforum/IT/issues/18
https://github.com/smartcontractresearchforum/IT/issues/19

**Comment by liberty7369** [comment]
Perfect! Who would should be invited?

**Comment by vincenzospaghetti** [comment]
I believe this ticket can be closed out. @SirAh0 @zubepaul 

To my knowledge, Brian will be conducting skill shares each month and, as needed, can include a focus on Github. There may be an opportunity for Brian to create a 'how to github with scrf' video - of which can fold into this open ticket: https://github.com/smartcontractresearchforum/engagement/issues/68
