### ISSUE TITLE
Welcome Packet for Full Time Contractors

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#67]
This project is about creating a Welcome Packet for full-time employees who join SCRF. This is an additional onboarding asset to what we already have and would include the following:
- PDF Packet itself (no more than 30 pages about working with SCRF)
- Swag (t-shirt, stickers, etc.)
- Discord Nitro
- Anything else SCRF wants to give full-time employees as they start with us

**Comment by zubepaul** [comment]
@Wood-Jack Use this issue to pull all the documents together.

**Comment by Wood-Jack** [comment]
Ok will do @zubepaul

**Comment by zubepaul** [comment]
Next step is to make checklist
Also refer to the meeting notes from the [Engagement Vertical meeting on August 1](https://github.com/smartcontractresearchforum/engagement/issues/129)

**Comment by Wood-Jack** [comment]
First Draft Due Date: Aug 9th,

**Comment by zubepaul** [comment]
This needs a stronger proposal that help guides what needs to be accomplished by this. Minimally goals. This is for community onboarding, so can be a simpler version than the hiring onboarding welcome packet that is associated with a specific position.

**Comment by zubepaul** [comment]
Connected somewhat to #161 and need to consolidate efforts. It appears this issue is currently focused on gathering what people would need in one place. 

@Wood-Jack please link an updated documented to this issue with the list of needed and existing documents

**Comment by Wood-Jack** [comment]
Connecting with SCRF: https://github.com/smartcontractresearchforum/docsfork/blob/main/en/content_connecting_with_scrf.md
Public Calendar: https://calendar.google.com/calendar/u/0/embed?src=null@scrf.io&ctz=America/Los_Angeles
Projects By Vertical(departmentt): https://github.com/orgs/smartcontractresearchforum/projects?query=is%3Aopen
SCRFTerms and titles: https://docs.google.com/document/d/1_6v1vVUEV12UpSP8hN0Fq-TmvgHWEIejuiv6Cz1h23E/edit?usp=sharing 
Community Bootcamp Slides (Not sure if link will work for this said restricted access): https://docs.google.com/presentation/d/12JuLCMNb6ZLnt5nTsF4UejA47brh4QO-3LdSs3T6DX4/edit?usp=sharing

**Comment by Wood-Jack** [comment]
How to contribute: https://github.com/smartcontractresearchforum/docs/blob/main/en/grants_general_contributors.md
