### ISSUE TITLE
Organize Document Library for Onboarding

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#72]
This is a project to organize all of the documents (public and private) in an Onboarding/Engagement or overall SCRF folder. The community needs easy access to documents as they acquire the need for them and internal to have a centralized location for documents. The problem today is that everything exists in individual contributors' heads and is shared as needed through links. This is often confusing and disorienting as everyone is then in charge of personally managing document organization for themselves. This lacks cohesion and makes it difficult to share information and onboard both internal folks and the community.

**Comment by Wood-Jack** [comment]
Yea sounds good and where would you want this document organization structure placed in?

**Comment by vincenzospaghetti** [comment]
This would be for organizing the shared SCRF Google Drive.

May also apply to GitHub but Maria and Victoria are already working on
public facing documents.

Valerie Spina

**Comment by Wood-Jack** [comment]
Ok sounds good and just need the link and I can take a look at it

**Comment by Wood-Jack** [comment]
Ok I see the file structure in the article

**Comment by zubepaul** [comment]
@vincenzospaghetti I am not certain that an overhaul of the structure is necessary so much as a sorting of role permissions and communicating the structure in place. This does seem like something that @SirAh0 and @Wood-Jack could collaborate on.

**Comment by vincenzospaghetti** [comment]
I do think we need an overhaul. I'm not sure the current drive organization
is user-focused or intuitive. Access needs organization for sure, but for
example, with Onboarding, most of those documents and presentations should
be public (lowest access level) along with anything that explains the
functions, operations, or organization of SCRF. Right now the default SCRF
Drive is 3 folders with nothing in them.

[image: image.png]

**Comment by Wood-Jack** [comment]
Here is my plan so far for organizing the documents in SCRF Drive. https://docs.google.com/document/d/1WJfn6fLG1-DboAmoRce2DDAI0DhgudG-Exd5-8WfB8M/edit?usp=sharing . Would you please look over @zubepaul and @vincenzospaghetti  I would like to hear your thoughts on the draft.

**Comment by vincenzospaghetti** [comment]
Great start! Added some comments in the doc. Generally I would like to see
it built out more.

**Comment by Wood-Jack** [comment]
Current update:

- [x] @Wood-Jack  getting file folder structure information frm Twan

- [x] @0xAngle getting file folder structure infromation from Eugene and Maria

- [x] Reconvene at a time and add last remaining file structure into documentation

Also don't forget to ask which files they want public or private.

**Comment by zubepaul** [comment]
The focus of this is to make sure that our onboarding materials are all in one place, that we can all access it as we need to for onboarding, and the that documents support the onboarding goals.

**Comment by zubepaul** [comment]
This is primarily done, but suggests there are more documents to make in the future.
