### ISSUE TITLE
Fill in document tracking for all hires and current contractors

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/engagement#76]

**Comment by vincenzospaghetti** [comment]
@LorrettaGS and @liberty7369 can we partner to fill in this document with current contractors and in-the-pipeline folks?

We need a full directory of people.

I am looking to use this document to do so:
https://docs.google.com/spreadsheets/d/1GoLgXPF3SFpkUTUQDbkdcoGJ2rX13XNyGrsWVFrY4nY/edit#gid=0

**Comment by liberty7369** [comment]
Yes. I am meeting with Lorretta today.

**Comment by zubepaul** [comment]
This task is done. The current document might need future revision, but the initial task is completed.
