### ISSUE TITLE
GTM Spreadsheet Migration

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#84]
Migrate vital information from the GTM spreadsheet to the GTM Project board. This will also include moving files from the GTM folder to the new Engagement GTM folder.
###Items to accomplish
- [x] Confirm access to the [GTM Spreadsheet](https://docs.google.com/spreadsheets/d/1OAhoXcCd2kuwxvU4TibUTB-klTKtd92vcKtGTL_8Lvk/edit#gid=0), the [Go To Market Tracking](https://github.com/orgs/smartcontractresearchforum/projects/14) board, the [original GTM](https://drive.google.com/drive/u/0/folders/13ryoLtCcGn1vJ7XaYEXdCgv9fUVvFxqr) folder and the [Engagement GTM](https://drive.google.com/drive/folders/1ynqau7ET4BSCmgdzPRzz8H7fyolhFEHM) folder.
- [x] Using the issues from the Content Pipeline, replace all of the "draft" entries in the Go To Market board
- [x] Using the old GTM spreadsheet, update the Go To Market board
- [x] Check that all new issues moving through the content pipeline are represented on the Go To Market board

**Comment by zubepaul** [comment]
@Fizzymidas migration of files was able to be automated. Is the GTM project board now up-to-date?

**Comment by Fizzymidas** [comment]
Great, I followed up earlier about the access permissions, so cool to know that part is automated.

Yes, regarding all existing issues from the content pipeline, the GTM Board is now up to date.

I have a question as to how to know when a new content issue is created, so as to update it on GTM when it hits the forum.

**Comment by zubepaul** [comment]
@Fizzymidas There is no current automation that provides notification as far as I know. Perhaps we can make this a weekly task to update the GTM board

**Comment by Fizzymidas** [comment]
alright then.
