### ISSUE TITLE
Organize the Hiring folder on Drive

### ISSUE THREAD

**Issue by zubepaul** [smartcontractresearchforum/engagement#92]
The purpose of this ticket is to organize the hiring folder on the Engagement team drive.

**Comment by zubepaul** [comment]
Needs an organizational plan for the folder and sharing permissions
- JDs
- Performance reviews
- General notes
- Open question if more confidential information is going to be captured.

This is likely going to be core + 
@Wood-Jack will help to create the folder structure.

**Comment by Wood-Jack** [comment]
Hi @ttaloute I have a doc I'm working on currently and I added the hiring folder inside so let me know what you think about the organization of the folder. Here is the link: https://docs.google.com/document/d/1WJfn6fLG1-DboAmoRce2DDAI0DhgudG-Exd5-8WfB8M/edit?usp=sharing

**Comment by Wood-Jack** [comment]
Current Update:

- [ ] Adding contractors individual file folders into the documentation

Overall ticket will be complete when ticket #72 is complete

**Comment by Wood-Jack** [comment]
Added the contractors that were in core into the organizing documents
